services:

  postgres:
    image: postgres:16.0-alpine3.17
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    volumes:
      - ./.data/minio:/data
    ports:
      - 9000:9000

    command: server /data
